# --- Initialization & Bootstrapping ---
$sdkPath       = "C:\ProgramData\PatchMSIX\SDK"
$workDir       = "C:\ProgramData\PatchMSIX\Work"
$outputDir     = "C:\ProgramData\PatchMSIX"

# Dynamically detect YOUR current OS Build (e.g., 19044)
$currentOSBuild = [System.Environment]::OSVersion.Version.Build
$newVersion     = $currentOSBuild.ToString()

$pfxPassword   = "Password123"
$timestampUrl  = "http://timestamp.digicert.com"

# 1. Ensure environment is ready
Write-Host "[0/10] Checking environment..." -ForegroundColor Cyan
Write-Host "Detected Your OS Build: $currentOSBuild" -ForegroundColor Gray

$Package = Get-AppxPackage | Where-Object { $_.Name -like "*Microsoft.MsixPackagingTool*" }

if (-not $Package) {
    Write-Host "MSIX Packaging Tool not found. Attempting install..." -ForegroundColor Yellow
    winget source update
    winget install --id "Microsoft.MSIXPackagingTool" --accept-source-agreements --accept-package-agreements --silent
    $Package = Get-AppxPackage | Where-Object { $_.Name -like "*Microsoft.MsixPackagingTool*" }
}

if (-not $Package) {
    Write-Host "`n[!] Could not install automatically. Please install 'MSIX Packaging Tool' from the Store." -ForegroundColor Red
    return
}

if (-not (Test-Path $sdkPath)) { New-Item -ItemType Directory -Path $sdkPath -Force | Out-Null }

if (-not (Test-Path (Join-Path $sdkPath "makeappx.exe"))) {
    Write-Host "Copying SDK environment..." -ForegroundColor Yellow
    $binFolder = Get-ChildItem -Path $Package.InstallLocation -Filter "makeappx.exe" -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1 | ForEach-Object { $_.DirectoryName }
    if ($binFolder) { Copy-Item -Path "$binFolder\*" -Destination $sdkPath -Recurse -Force -ErrorAction SilentlyContinue }
}

# 2. File Chooser
Add-Type -AssemblyName System.Windows.Forms
$FileBrowser = New-Object System.Windows.Forms.OpenFileDialog -Property @{
    InitialDirectory = [Environment]::GetFolderPath('UserProfile') + "\Downloads"
    Filter = "MSIX Files (*.msix)|*.msix"
    Title = "Select MSIX to Auto-Patch for Build $currentOSBuild"
}
if ($FileBrowser.ShowDialog() -ne "OK") { return }
$msixPath = $FileBrowser.FileName

# 3. Prepare Workspace
if (Test-Path $workDir) { Remove-Item $workDir -Recurse -Force -ErrorAction SilentlyContinue }
New-Item -ItemType Directory -Path $workDir -Force | Out-Null
if (-not (Test-Path $outputDir)) { New-Item -ItemType Directory -Path $outputDir -Force | Out-Null }
$extractDir = Join-Path $workDir "Extracted"
$pfxPath    = Join-Path $workDir "AutoGeneratedCert.pfx"

# 4. Tool Paths
$makeAppxPath = Join-Path $sdkPath "makeappx.exe"
$signToolPath = Join-Path $sdkPath "signtool.exe"

# 5. Unpack
Write-Host "[1/10] Unpacking MSIX..." -ForegroundColor Cyan
& "$makeAppxPath" unpack /p "$msixPath" /d "$extractDir" /l

# 6. Read Identity & Detect Target Version Automatically
$manifestPath = Join-Path $extractDir "AppxManifest.xml"
[xml]$manifest = Get-Content $manifestPath

$publisherName = $manifest.Package.Identity.Publisher 
$packageName   = $manifest.Package.Identity.Name

# Find the version currently required by the package
# We look for the MinVersion in the TargetDeviceFamily tag
$targetToReplace = $manifest.Package.Dependencies.TargetDeviceFamily.MinVersion
# MSIX versions are often 10.0.19045.0, so we extract the build number (the 3rd part)
if ($targetToReplace -match "\d+\.\d+\.(\d+)\.\d+") {
    $detectedBuild = $Matches[1]
    Write-Host "Detected Package Requirement: $detectedBuild" -ForegroundColor Yellow
} else {
    Write-Warning "Could not auto-detect version in manifest. Defaulting to replace '19045'."
    $detectedBuild = "19045"
}

# 7. Create & Trust Certificate
Write-Host "[2/10] Creating & Trusting Certificate for $publisherName..." -ForegroundColor Yellow
$cert = New-SelfSignedCertificate -Type Custom -Subject $publisherName `
    -KeyUsage DigitalSignature -FriendlyName "MSIX_Development_Cert" `
    -CertStoreLocation "Cert:\LocalMachine\My" -TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.3")
$securePassword = ConvertTo-SecureString -String $pfxPassword -Force -AsPlainText
Export-PfxCertificate -Cert $cert -FilePath "$pfxPath" -Password $securePassword | Out-Null
Import-PfxCertificate -FilePath "$pfxPath" -CertStoreLocation "Cert:\LocalMachine\TrustedPeople" -Password $securePassword | Out-Null

# 8. Patch Manifest (The Auto-Replace)
Write-Host "[3/10] Patching Manifest ($detectedBuild -> $newVersion)..." -ForegroundColor Yellow
$xmlText = Get-Content $manifestPath -Raw
$newXmlText = $xmlText -replace $detectedBuild, $newVersion

$Utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($manifestPath, $newXmlText, $Utf8NoBom)

# 9. Repack and Sign
$fileName = Split-Path $msixPath -Leaf
$newFileName = ($fileName -replace "\.msix$", "") + "_Patched.msix"
$newMsixPath = Join-Path $outputDir $newFileName
if (Test-Path (Join-Path $extractDir "AppxSignature.p7x")) { Remove-Item (Join-Path $extractDir "AppxSignature.p7x") -Force }

Write-Host "[4/10] Repacking MSIX..." -ForegroundColor Cyan
& "$makeAppxPath" pack /d "$extractDir" /p "$newMsixPath" /o

Write-Host "[5/10] Signing..." -ForegroundColor Cyan
$absMsix = (Resolve-Path "$newMsixPath").Path
$absPfx  = (Resolve-Path "$pfxPath").Path
& "$signToolPath" sign /f "$absPfx" /p $pfxPassword /fd SHA256 /tr $timestampUrl /td SHA256 "$absMsix"

# 10. Install
if ($LASTEXITCODE -eq 0) {
    Write-Host "[6/10] Checking for existing installation..." -ForegroundColor Yellow
    $existingApp = Get-AppxPackage -Name $packageName
    if ($existingApp) {
        Remove-AppxPackage -Package $existingApp.PackageFullName
    }

    Write-Host "[7/10] Installing patched MSIX..." -ForegroundColor Green
    Add-AppxPackage -Path "$absMsix"
    
    Write-Host "[8/10] Success! Application installed." -ForegroundColor Green
    if (Test-Path $workDir) { Remove-Item $workDir -Recurse -Force }
    Write-Host "[9/10] Workspace cleaned." -ForegroundColor Gray
    Write-Host "[10/10] Process Complete." -ForegroundColor Cyan
} else {
    Write-Host "`n[!] Signing Failed." -ForegroundColor Red
}
